# Generated by Django 3.0.3 on 2020-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
