# Generated by Django 3.0.3 on 2020-02-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
