# Generated by Django 3.0.3 on 2020-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.CharField(max_length=200, verbose_name='price')),
            ],
            options={
                'db_table': 'yess',
            },
        ),
    ]
