# Generated by Django 3.0.3 on 2020-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kyobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('price', models.CharField(max_length=200, verbose_name='price')),
            ],
            options={
                'db_table': 'kyobos',
            },
        ),
    ]
