# Generated by Django 3.0.3 on 2020-02-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyobo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyobo',
            name='author',
        ),
    ]
