# Generated by Django 3.0.3 on 2020-02-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='이메일')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
